/**
 * Countries of the world for the map widget's heat mode: a 1° grid (360 × 180, row 0 = 89–90° N,
 * column 0 = 180–179° W) holding each cell's country (index + 1 in COUNTRIES, 0 = sea), run-length
 * encoded as (value, run) byte pairs. Generated from Natural Earth 1:110m admin-0 countries (public
 * domain, via the world-atlas package) and ISO 3166 codes (i18n-iso-countries), so it works offline.
 * COUNTRIES: [ISO alpha-2 ('' when none), English name, centre latitude, centre longitude].
 */
export const COUNTRY_GRID_WIDTH = 360;
export const COUNTRY_GRID_HEIGHT = 180;
export const COUNTRIES: [string, string, number, number][] = [["FJ","Fiji",-16.5,-0.5],["TZ","Tanzania",-6.2,34.8],["EH","W. Sahara",24,-12.4],["CA","Canada",56.6,-99.7],["US","United States of America",39,-98.8],["KZ","Kazakhstan",48,67.2],["UZ","Uzbekistan",41.7,63.1],["PG","Papua New Guinea",-6.7,144.3],["ID","Indonesia",-0.4,114],["AR","Argentina",-34.5,-64.9],["CL","Chile",-36.2,-71.5],["CD","Dem. Rep. Congo",-2.8,23.6],["SO","Somalia",4.9,45.9],["KE","Kenya",0.7,37.8],["SD","Sudan",15.9,29.8],["TD","Chad",15.2,18.6],["HT","Haiti",18.8,-72.8],["DO","Dominican Rep.",18.8,-70.3],["RU","Russia",60.1,87.1],["BS","Bahamas",25.4,-78],["FK","Falkland Is.",-51.5,-59.5],["NO","Norway",63.4,13],["GL","Greenland",74.1,-41.2],["TF","Fr. S. Antarctic Lands",-49.5,69.5],["TL","Timor-Leste",-8.5,126.5],["ZA","South Africa",-29,25.1],["LS","Lesotho",-29.5,28],["MX","Mexico",23.8,-102.4],["UY","Uruguay",-32.7,-56],["BR","Brazil",-10.4,-53.3],["BO","Bolivia",-16.7,-64.7],["PE","Peru",-8.7,-74.6],["CO","Colombia",3.9,-73.2],["PA","Panama",8.6,-80.6],["CR","Costa Rica",9.9,-84.1],["NI","Nicaragua",13,-85],["HN","Honduras",14.8,-86.6],["SV","El Salvador",13.5,-89],["GT","Guatemala",15.8,-90.1],["BZ","Belize",17,-88.5],["VE","Venezuela",7.1,-66],["GY","Guyana",4.8,-59.1],["SR","Suriname",4,-55.8],["FR","France",46.5,2.2],["EC","Ecuador",-1.5,-78.4],["PR","Puerto Rico",18.5,-66.5],["JM","Jamaica",18.1,-77.3],["CU","Cuba",21.7,-79.1],["ZW","Zimbabwe",-19.2,29.7],["BW","Botswana",-22.1,23.9],["NA","Namibia",-22,17.2],["SN","Senegal",14.5,-14.4],["ML","Mali",17.1,-3.6],["MR","Mauritania",20.1,-10.2],["BJ","Benin",9.8,2.4],["NE","Niger",17.3,9.3],["NG","Nigeria",9.4,7.9],["CM","Cameroon",5.8,12.6],["TG","Togo",8.5,1.1],["GH","Ghana",7.9,-1.2],["CI","Côte d'Ivoire",7.3,-5.7],["GN","Guinea",10.5,-11.1],["GW","Guinea-Bissau",12.2,-15.2],["LR","Liberia",6.6,-9.5],["SL","Sierra Leone",8.5,-12],["BF","Burkina Faso",12.4,-1.6],["CF","Central African Rep.",6.5,20.3],["CG","Congo",-1,15.1],["GA","Gabon",-0.6,11.5],["GQ","Eq. Guinea",1.5,10],["ZM","Zambia",-13,28],["MW","Malawi",-12.9,34.2],["MZ","Mozambique",-17.3,35.4],["SZ","eSwatini",-26.5,31.5],["AO","Angola",-11.6,17.6],["BI","Burundi",-3.5,30],["IL","Israel",32.5,35.5],["LB","Lebanon",33.5,35.5],["MG","Madagascar",-19.8,46.5],["PS","Palestine",31.9,35.2],["GM","Gambia",13.5,-15.5],["TN","Tunisia",34,9.4],["DZ","Algeria",28.1,2.5],["JO","Jordan",31.1,36.6],["AE","United Arab Emirates",23.8,54.3],["QA","Qatar",25.5,51.5],["KW","Kuwait",29.5,47.5],["IQ","Iraq",32.9,43.8],["OM","Oman",20.7,56.3],["VU","Vanuatu",-15.6,167.2],["KH","Cambodia",12.8,105.2],["TH","Thailand",15,101.1],["LA","Laos",18.7,103.6],["MM","Myanmar",20.8,96.6],["VN","Vietnam",17,106.2],["KP","North Korea",40.1,127.3],["KR","South Korea",36.4,127.5],["MN","Mongolia",46.8,102.8],["IN","India",22.7,79.5],["BD","Bangladesh",23.6,90.4],["BT","Bhutan",27.5,90.5],["NP","Nepal",28.2,84],["PK","Pakistan",29.8,69.2],["AF","Afghanistan",33.7,65.9],["TJ","Tajikistan",38.5,71.2],["KG","Kyrgyzstan",41.4,74.4],["TM","Turkmenistan",39,59.5],["IR","Iran",32.4,54.5],["SY","Syria",35,38.5],["AM","Armenia",40,45],["SE","Sweden",60.6,15.1],["BY","Belarus",53.4,28.4],["UA","Ukraine",49,31.1],["PL","Poland",52,19.3],["AT","Austria",47.8,14.4],["HU","Hungary",47.2,19.4],["MD","Moldova",47,28.5],["RO","Romania",45.9,24.9],["LT","Lithuania",55.2,24.2],["LV","Latvia",56.8,24.4],["EE","Estonia",58.7,25.8],["DE","Germany",51.1,10.2],["BG","Bulgaria",42.7,25.3],["GR","Greece",39.3,22.6],["TR","Turkey",39,35.6],["AL","Albania",40.8,19.8],["HR","Croatia",45.1,16.4],["CH","Switzerland",46.9,8.2],["LU","Luxembourg",49.8,6],["BE","Belgium",50.5,4.5],["NL","Netherlands",52.1,5.3],["PT","Portugal",39.7,-7.9],["ES","Spain",40.3,-3.6],["IE","Ireland",53.5,-7.8],["NC","New Caledonia",-21,165],["SB","Solomon Is.",-7.5,158.5],["NZ","New Zealand",-44,170.7],["AU","Australia",-25.5,134.2],["LK","Sri Lanka",7.7,80.8],["CN","China",36,103.7],["TW","Taiwan",23.5,120.8],["IT","Italy",43.6,12.2],["DK","Denmark",56.3,9.5],["GB","United Kingdom",54.1,-2.7],["IS","Iceland",64.5,-18.5],["AZ","Azerbaijan",40.2,47.6],["GE","Georgia",42,44],["PH","Philippines",15.5,121.4],["MY","Malaysia",3.6,114.9],["BN","Brunei",4.5,114.5],["SI","Slovenia",46.5,16],["FI","Finland",62.8,26],["SK","Slovakia",48.5,19.2],["CZ","Czechia",49.8,15.5],["ER","Eritrea",15.6,38.3],["JP","Japan",35.9,136.5],["PY","Paraguay",-23.2,-58.3],["YE","Yemen",15.9,47.6],["SA","Saudi Arabia",24,44.6],["AQ","Antarctica",-75.7,79],["","N. Cyprus",35.3,33.7],["CY","Cyprus",34.9,33.1],["MA","Morocco",29.7,-8.7],["EG","Egypt",26.4,29.8],["LY","Libya",27,18],["ET","Ethiopia",8.7,39.5],["DJ","Djibouti",12,42.5],["","Somaliland",9.7,46.3],["UG","Uganda",1.4,32.4],["RW","Rwanda",-1.8,29.8],["BA","Bosnia and Herz.",44.1,17.7],["MK","Macedonia",41.5,21.5],["RS","Serbia",44.1,21],["ME","Montenegro",42.5,19],["XK","Kosovo",42.5,21],["TT","Trinidad and Tobago",10.5,-61.5],["SS","S. Sudan",7.4,30.1]];
export const COUNTRY_GRID_RLE_BASE64 =
  'AP8A/wD/AP8A/wD/AP8A/wD/AAYXDAD/AC4EAgABBBUADxcZAP8AJAQZAAQXJwACFwkA/wAVBAcABgQNAAMXMwAjFgIAARYDABYT' +
  'BAApEwYApwQVAAgXLwAeFggAAhYEAEQTBwCTBAMABQQFAAEEAwADBAQAAQQNAAIXNQAgFgcAURMFAIgEAwAEBAEAEAQBAAYECgAJ' +
  'FzIAIRYEAAQWAQBQEwIAhQQEAAgEAgAHBAMAAgQFAAIECgAJFzEAVhMEACATCwCDBAcAAQQDAAUEAwACBAIAAQQGAAEEBQAWFycA' +
  'TRMGABsTGAAXEwgAZQQCABYEBgABBAEAGRclAEwTAwAbExgAfgQIAAkEAgAEBAQAAQQFAAIEAwACBAIAAQQDABYXIwBLEwMAGBMg' +
  'AAETBQAEEwQADRMDAFwEBgABBAkAAQQDAAMEBQABBAIABAQJAAMEAQAWFyEAShMEAA0TBAAIEzAAChMGACQTDQAqBAQAAQQOAAUE' +
  'AwABBAMAAwQQAAEEAQARFyEAShMEAAwTBAABEwIAARM1AAMTAQACEwIAARMNADAFCgAlBAsABwQEAAMEFAAOFx0AAhcBAC8WBwAk' +
  'EwYAARNWACUFFgQCAAQEDwADBA4AAwQEAAEEBAAFBAQABQQKAA0XAgABFxsAKhYImAMWAhMCABsTBAADEwYAARNeAAITCAADEwwF' +
  'GgQbEwYEAxMHBAETAwQGEwIEBRMGBAcTYAAKEw4AAhMDAAoTAgAFEwEAbRMMBRcENRMBBAYTBAQCEwIECRNeAAsTAwACEwIAGRMC' +
  'AG4TAQADEwYFARMCBRUEOhMJBAwTXAADEwIABhMDABwTAQBrEwEABxMEBRsENhMBBAETCwQGEwMEAhNdAAUTBQCSEwEACAUBAAMF' +
  'FAQ1AAIEBAAEBAMAAQQIAA4XCwATkQcAGhYDbwcAA5gGEwUAAhONAAoFAgAJBRQEMgAFBAIAAgQBAAkEBwAOFwoAMhYDbwgAApgI' +
  'E5UAEAUYBDEACAQCAAQEAQAHBAMAERcHADEWBm8GAAOYChOSAAETAQAPBRkELwAQBAYAFxcGADAWB28FAASYCRN/AAITAwACEwkA' +
  'FgURAAIFBQQvABAECAAYFwMAMBYHbwYABJgGE38ABxMJABsFCAACBQIACgUCBAIFAQQoABEECQADBAIARRYHbwYAB3kCAAETeQAC' +
  'EwQABRMDACgFAwAQBQQEKQAPBAoAAQQEADqQAgAJFgMAAm8GAAd5AxNyABITAwAoBQIAAQUDABIFAQQoABAEDwA4kAQADI8BAAFv' +
  'BQAFeAEAAXgCeQETcQAREwYAJQUCABoELAALBA8AOJADAAuPAwABbwQABXgHE24AEhMHACIFAgAdBQIELAAIBBIANpAEAAqPAgAB' +
  'jwJvAQAHdwZwBBNpABMTBwAhBQEAIQQxAAIEFwAwhgKQAQACkAMACnoBAAZyAwABEwN3A3AFEyIGBhNCABMTBQBCBAEAAwQvAAME' +
  'FwAvhgMAA5ADAAd6B3IKcAkTHAYMEwEGBBM/AAETAQANEwQASAQuAAMEFwAvhgIAA5AGAAKDA3oHcglwCRMdBhITKowFEw8AARMB' +
  'AA0TAgBKBDAAAQQWAAEEAQAzkAUAA4MCeglyCXEEcANxAxMQBgMTCAYSExNiAxMTjAcTDgABEwEADhMBAEoEAQABBEIAAwQBADOQ' +
  'AgAELAKCA3oHmgNyCHEMEw0GIxMHYgITBWIEExGMCBMOAAETAgBZBAIAAQQ5AAMEAgAEBAIAAQQBADQsCHoHmgZyBHEREwcGKBMC' +
  'YhMTBWIDjA0TCwACEwIAXQUeBBgAAQQDAAYEBgAwLA16BXMEmQN0AZkBcRITBwYnjAJiHIwPEwkAAhMBAF0FAQABBSQEFQAJBAEA' +
  'AQQBADIsCoADegFzBnQFdgV1AnEJEwoGJowEYh2MDxMFAAMTAQBdBScEDwUCBAMAAQQBAAIEAQA6LAiABI4EcwGXAnQEdgd1AnEB' +
  'AAFxAwADEwsGAQADBh6MCGIajBETBAAEEwIAXAUpBAwFAwQHADwsCI4GAAF/Ba0CdgdxAgADEwIAAhMLAAUGBQcBBheMCWIYjBIT' +
  'BABjBSoEBgUIAAIEAgA/LAiOBQADfwGrA60EdgYACRMJAAMGBgcFBhOMDmIRjBQTBQAGnAEAXQUqBAMFCQA+hQMAAywJAAOOBAAC' +
  'fwGrAq0EewUADBMIAAMGBQcJBhCMD2IPjBQTBAAGnAQAWwUpBAMFCQA+hQosAgAIjgMABK4CrwKtAXsFAA6TAxMDAAUGAwcCawEH' +
  'BwYFagmMFmIGjBZgAQAJnAQAXAU1AD6EA4UIAAqOBAADfgGsA3sBfAF7AXwBfQEABH0FAAR9ApMDkgETAZIBAAVrAQYBBwFrAwcH' +
  'BgIHAWoIjDJgAgBqBTIAQYQChQgAB44CAAWOAwABfgJ8AwACfQEAAn0PbgGSBQADawkHB2kBBwJqA4wBagGMLAABjANgBAALnAIA' +
  'XgUyAEGEAoUHAAiOAgAGjgEAA3wDAAN9EmwBbgGSAwAEawoHBWkDagOMLQADjAEAAmADAAycAgBfBTAAQoQChQcAFXwDAAN9EWwE' +
  'kgEABWsLBwNpB4wrAAdgAwAMnAEAYAUvAEOEAoUGAA6OAgAGfAIABH0SbAUABGsBbARrCAcBaQFoAmkEjCwAAYwCAARhAwAJnAMA' +
  'YQUuAEaFAQAGUwdSAwALfAEABn0CAAF9AgACfQFtBVgDbBBrBGgHZwSMLQAFYQMAB5wFAGIFLQBGowEAA1MKUgMAGW0FWAVsD2gB' +
  'awFoCWcGjCoAB2ECAAScCABjBSsARqMFUwpSAgAabQVYBWwPaApnA2MFjCkABmEBAAScAwABnAIAaQUnAEejBlMKUgMAGE4BbQNY' +
  'B2wPaAlnBGMFjCoACZwEAG0cAgUjAEejCFMJUgOlBAAGpQIADE0BbQFUAlgIbA5oCGcGYwOMKwAJnAIAbxwCAAEcAgUEHAIFGQBH' +
  'owZTDVIBpQYABKUFpAIAA6QBAARUAp8EWAdsDWgHZwZjBYwrAAicAQBxHAEAAhwIBRgAR6MFUw5SAaUJAAGlBaQKVAOfBVgFbA5o' +
  'BGcIYwaMKQB8HAEAAhwIBQEcAgUGAAQFAgAGBQIAR6MDUxGlD6QHAAGkAlQBnwhYA1cBAAJsC2cBaAJnCWMHZgOMJwB8HAEAARwM' +
  'BQQADQUCAEajAlMTpQ+kCQABnw0AA2wLZwpjCWYEjAhjA4waAHscAwABHAsFAwAOBQMAQ6MEUxOlD6QIAAOfDQAEbApnB2MNZgVj' +
  'AWUDYwVeAowWAH4cAQADHAoFAgAPBQIAARQBAECjAgMDNgJTEaUPpAkAAp8OAAdsBmcHYxFmAWMHXgSMFQCAHAEAAhwMABAFAQBB' +
  'owM2BlMQpQ+kCgACnw0AAVYBAAdsA2cJYxJkAWMFXgOMFQCBHAEAAxwKAFOjAgMBNgY1AlMOpQ+kCgACnw4AA1UCWQEACmcEYxFk' +
  'BGMCXgSMFQACjQEAgxwJAFKjAgMCNgY1A1MPpQ2kCwADnw1VBFkDAAljFWQCYwJeBowSAAONAQCFHAgADjABAAEwAwA/owIDATYH' +
  'NQVTCzgFEAOlB6QLAAOfEFkFAApjE2QCAAFkAV4GjANfBYwIAAWNAQCGHAgAEjACADyjAgMCNgc1BlMIOAcQBaUFDwwAAp8QWQQA' +
  'C2MRAAVkAV4IjAFdAV8FAAGMAgCPHAkABxwDAAowAgA7Ngo1CFMFOAkQBqUDDwwAA58PWQQADmMOAAZeB10FXwIAYQUBADIcCQAF' +
  'HAQADhEBEgIANjYKNQlTAjgLEAgPDQAEnw1ZBAAPYwwACV4EXANdA18CAAOMAgCRHAkAAhwFAA4RAhIEAAEuAQAyNgo1CjgLEAkP' +
  'DgADnwieA1kFABBjCwAKXgRcA10EXwEAA4wBAJUcCicCKAEASDYKNQo4CxAJDw6bAQADnwGeAZ8EngVZAgASYwoAC14EXAddAV8B' +
  'AA2UAgCLHAgnAigBAEc2AjQBNgg1CjgLEAkPDZsCAASeCgAUYwkADF4FXAZdAl8BAAyUAgCRHAEnBCUEAEM0BDYHNQk4CxAJDw6b' +
  'AwADngkAFmMGABJeAVwHXQFfAgALlAIAkicDJQQkAgBCNAU1CkICOA4QCA8OmwKmApsBAAKeBgAZYwYAEl4BXAZdAVsBXwIAC5QC' +
  'AJQmAiUBJAMAQ1EDNAI1CUIEOAM5AjgIEAgPDqYGAAGeBAAcYwUAEl4BXANbBl8BAA2UAgCVJAQAQjQBPwI+ATQBNQhCBjgCOQo6' +
  'ARAHDw6mBqcBACBjBQASXgFcAQACXAFbBV8BAA+UAQCVJAIACyEBADg/AT4HNQNCBjcDOQo6ARAIDwmxAQ8CpgenAQAGDQIAGWME' +
  'ABNcAQADWwNfAwANlAEAApQBAJQjAwAHIQMpAQABKQUAAikCsAEALj4HNQNCAjwDOwE3AzkJOgIQB0MBDwmxAQ8BpgmoAQABqAQN' +
  'AgAZYwQAEl4BAAVfAwAMlAEAnCMBIgEAAiIBAAMhAykBAAEpCgAvPgFBAj4DPQU8AzsBNwI5CjoBEAdDAg8CsQMPAbEFpgmoBg0C' +
  'ABljAwABiwEAEVwBAAZfAQAMlAEABpQBAJYjASIDAAIiASEEKQ0AL0ECPgM9BTwEOwE3ATkJOgMQBEMFsQqmDKgCDQIAG2MBAAKL' +
  'AQARXAIAF5QBAAGUAQCZIgEAAiEGKQsqAgAuQQJAAz0FPAQ7ATcBOQk6AxABQwmxCaYNDQMAHosCABFcAQAWlAEAAZQDAJwhBykJ' +
  'KgMAL0ACPQY8BDsBNwE5BzoFQwuxCaYLDQMAH4sCABKVAVwBAA6VAgAGlAEAnSEKKQcqBCsDLAEAK0ACPQU8AwAFOQQ6BUMNsQim' +
  'Cg0EADOVAwANlQMApCEJKQceASoCKwQsAgAsPQEADTkCOgdDBAwCQwIMBbEBDAGxBA4CpgcNBQAwCQIAA5UCAAuWAZUEAKQhCikD' +
  'HgQqAisELAIeAQA9OgVDAkQBDA2pAw4FpgEOAg0FADIJAgAClQIACpUDCQEApCEMKQMeBCoDKwMsAR4CAD06BkQCDA2pBA4GDQUA' +
  'NAkCAAKVAgAHlQQJAwCjIQkeAykDHgUqAR4IADtGAkUCRAUMDKkFDgYNBAA2CQMAAZUBAAUJAZUFCQMACgkBAJctAyEHHhQAO0UF' +
  'RAQMDKkEDgcNAgA4CQQABgkJAAIJBAAECQEAly0FIAEhBB4VADpFBUQEDAypBA4HDQEAOgkEAAUJCQAOCQEAki0FIAIhBR4YADZF' +
  'BUQDDAyqAgIEDgYNAQA7CQMABgkHAAIJAwAJCQMAkS0EIAceGQABHgEANUUCRAQMDaoBAgcOBAA8CQUABAkHAAIJAwALCQEAAgkE' +
  'AIwtAiAHIQEeHwAyRQFEBAwNTAICBw4CAD4JBAAICQIAAwkBAAEJAQAECQEAAwkBAAIJCAgCAIggAS0BIAgeIQAxRAQMDgIKAEAJ' +
  'AwAQCQEADQkFCAQAhiAIHiYALwwSAgkAQQkCABAJAQALCQEAAwkDCAUAAggBAAEIAgB/IAgeJgAvSwUMDQIJAEMJAwAZCQEAAwkD' +
  'CAcABwgBAHwgBh4nADBLBAwCSwMMCAIJAEQJBgAZCQMIBgALiAEAeiAFHicAMEsJDAdHAgIIAEsJAQACCQIAAQkBAAEJAQADGQEA' +
  'DQkBCAIAAwgCAIUgBh4lADFLCQwHRwRIAQIGAE8JAQAECQEAFggCAAuIAgB4IAceAx8DHh0AMUsJDAdHBEgBAgYAbggBAIQgCB8E' +
  'HhwAM0sKRwIMAkcFSAJJAQICSQIAXIoBAAmKAQCMIAgfBR4aADNLC0cEDAJHA0gBSQcACE8BAFGKBgAFigEAjSAHHwgeFgA0SwlH' +
  'C0gCSQYACE8BAFCKBgAGigIAjCAHHwkeFQAzSwpHCUkDSAJJBQAHTwIATIoCAAGKBwAGigMAjCAGHwkeFQAzSwpHCEkESAJJBAAH' +
  'TwMASooMAAaKAwAjAf8BaABuIAEfDB4TADMzB0sEMwJHAjEGSQUABk8FAEmKEgABigUAIAEBAG8LAR8LHhIANDMJMgUxB0kDAAhP' +
  'BQBJihgAkAsCHwedAh8BHhIANTMIMgUxB0kCAAlPBQBIihoAjwsBHwedBB4SADUzCDIHMQRJAwAJTwUARYofAA+HAQB9CwIfBp0E' +
  'HhEANzMHMgcxBEkDAAhPBQBDiiIAEIcBAHwLAh8BCgIfAQoCnQYeDgA4MwYyCRoCSQUAB08FAEKKJACMCwMKBp0FHgsAOzMGMgca' +
  'BUkDAAlPBABCiiUAigsDCgmdBR4HAD4zBTIHGgVJAwAJTwMAQoonAIkLAwoKnQMeBwA/MwUaATICGgEyAhoGSQEADE8BAESKJwCI' +
  'CwIKC50DCgEeBQBAMwUaATIBGglKAUkBAFCKKACICwIKDJ0BCgEeBgBAMwUaDQBRiicAiAsBCg4eBwBBGgEzAxoMAFOKJwCHCwEK' +
  'DR4HAEMaChsCGgIAVIomAIcLAgoMHQIeBgBDGg4AVIomAIcLAgoMHQMeBABFGgwAVoolAIgLAQoMHQUeAQBGGgsAV4oKAAiKEgCI' +
  'CwIKDB0EHgEARxoJAFiKCQALigIAAYoNAIkLAgoMAAEdAwBJGgIAX4oDABCKAQABig4AiAsDCg0Aw4oMABeJAQBxCwIKDgDFigoA' +
  'GIkBAG8LAwoOAMWKCgAZiQEAbwsCCgwAyooBAAGKAgAciQMAbQsBCgoA7IkDAG0LAgoKAO2JAgBtCwIKBwDSigMAGIkCAAGJAQBu' +
  'CwIKCQDQigMAF4kDAHELAQoHANOKAQAXiQMAcQsDCgYA6YkDAHILAwoFAOqJBAByCwMKBQDriQIAcwsDCgYA/wBfCwQKBQD/AGAL' +
  'AwoFAIkYAQDXCwIKBAD/AGMLAwoDAAgVAwD/AFkLBAD/AGULBQoBAP8AZQsDCgMA/wBmCwEA/wD/AP8A/wD/AP8A/wD/AP8A/wD/' +
  'AFSgAgD/AGSgAQD/AGagAQDGoAEAnaADAHOgBgAsoAQABqAEAA+gBgCcoAMAcaAMABagQACSoAMAbKAaAAqgRwCKoAIAAqAFAF+g' +
  'BgACoB4AB6BRAIKgAwABoAYARKAEAAKgCgACoCwABaBYAHygBwABoAYAMqACAAKgSwAEoGMAeqAGADCguAA+oAIAAqACABKgBQAD' +
  'oAoABKADAAWgDAAtoLkAN6AKAAGgAwACoAcAAaABAAqgJgAvoLYAMKBRAC6gtwAyoEwAKqDAACagUwAroMQAIKADAASgTwAdoAUA' +
  'CKDLAB+gAwAKoEgAGqAIAA2gvwA0oEoAB6AGAAagCAAQoL4ALaBaABigygAuoF4ABKDbACqg/6BEAAugBQABoAcAFKD/oEYAIaAB' +
  'AP8A/wD/AP8A/wD/AO4=';
